#!/bin/bash
# I copied this part from olofm@spotify, it's suspposed to fix the issue that I
# lose sudo access on machines i ssh into when I run tmux.
if test "$SSH_AUTH_SOCK" ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
